### ISSUE TITLE
Regression: the expand/collaps subtags thing stopped working?

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1875]
After my latest merge, the triangle for expanding/collapsing subtags has become flaky for me - it works for the first tag in the list that has children, but not for tags further down the list.

I don't know what the cause is, but it might possibly maybe have something to do with the changes @smari and @JocelynDelalande made recently?

Or maybe it's unrelated. Either way, it's a bug. :-)

**Comment by JocelynDelalande** [comment]
> I don't know what the cause is, but it might possibly maybe have something to do with the changes @smari and @JocelynDelalande made recently?

I'm currently using my branch from #1871, expading/collapsing triangles are working.

/me passes the hot potato to @smari  ;-)

**Comment by douglatornell** [comment]
I can confirm this issue (or maybe worse) in 1.0.0rc1 installed from `mailpile_0.99.1~1.0201708040145-1_all.deb`.

When I created a 1st subtag it appeared under its parent, but after I toggled the expand collapse triangle the subtag has never appeared again. I have restarted mailpile to no avail. Also, adding an additional subtag to the same parent doesn't change things - neither subtag has ever been visible.

**Comment by ceylon23** [comment]
I can also confirm this in 1.0.0rc1 from github clone new install.
Upon the addition of a new account the 1st Tag of the account is displayed but the expand/collapse arrow seemingly does nothing and no subtags are shown. However, when you edit 1st Tag and view the Technical settings you can both see and make changes to the subtags listed.

**Comment by JocelynDelalande** [comment]
@ceylon23, thanks for reporting. I think this has been fixed
since. Are you able to test current master to confirm ?

Jocelyn

**Comment by ceylon23** [comment]
I did a git pull in the Mailpile directory and it responds that I have
the latest. The version on startup is listed as v1.0.0rc1. I also have
this on the profile page "This is Mailpile version 1.0.0rc1: *Your
Mailpile is up to date*." The result is the same. It is still not
displaying the subtags.

On Tue, Oct 10, 2017, at 04:50 PM, JocelynDelalande wrote:
> @ceylon23, thanks for reporting. I think this has been fixed
>  since. Are you able to test current master to confirm ?
> 
>  Jocelyn 
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/mailpile/Mailpile/issues/1875#issuecomment-335618814

**Comment by JocelynDelalande** [comment]
I cannot reproduce, it works perfectly for me, let's dig it :-).

@douglatornell @ceylon23 @BjarniRunar Which browser are you using ? Is it the same with another browser ?

**Comment by ceylon23** [comment]
I have tried with following all with the same results:

Chrome 61.0.2163.100 (Official Build) (64-bit)
Firefox 56.0.1 (64-bit)
Brave 0.18.36

ceylon



On Wed, Oct 11, 2017, at 04:02 AM, JocelynDelalande wrote:
> I cannot reproduce, it works perfectly for me, let's dig it :-).


> @douglatornell[1] @ceylon23[2] @BjarniRunar[3] Which browser are you
> using ? Is it the same with another browser ?> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[4], or mute the thread[5].> 


Links:

  1. https://github.com/douglatornell
  2. https://github.com/ceylon23
  3. https://github.com/bjarnirunar
  4. https://github.com/mailpile/Mailpile/issues/1875#issuecomment-335744786

**Comment by JocelynDelalande** [comment]
> I have tried with following all with the same results:
> 
> Chrome 61.0.2163.100 (Official Build) (64-bit)
> Firefox 56.0.1 (64-bit)
> Brave 0.18.36

Thanks. If you hit *edit* wheel on parent tag view, then go to *technical settings* section, then find your subtag and click *settings*, and go in *technical settings* section, What is checked in *display in toolbar* or *hide in toolbar* ? Does changing it changes any behaviour ?

**Comment by ceylon23** [comment]
Show in Sidebar is checked for each one. Changing it does not affect
the behavior.

On Mon, Oct 16, 2017, at 03:45 PM, JocelynDelalande wrote:
>> I have tried with following all with the same results:


>> Chrome 61.0.2163.100 (Official Build) (64-bit)
>>  Firefox 56.0.1 (64-bit)
>>  Brave 0.18.36


> Thanks. If you hit *edit* wheel on parent tag view, then go to
> *technical settings* section, then find your subtag and click
> *settings*, and go in *technical settings* section, What is checked in
> *display in toolbar* or *hide in toolbar* ? Does changing it changes
> any behaviour ?> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/mailpile/Mailpile/issues/1875#issuecomment-337035668

**Comment by BjarniRunar** [comment]
I have this fixed in my local tree. Will push up soon.
